const images = [
  require('./images/bw3.jpg'),
  require('./images/bw4.jpg'),
  require('./images/bw5.jpg'),
  require('./images/bw6.jpg'),
  require('./images/bw7.jpg'),
  require('./images/bw8.jpg'),
  require('./images/bw9.jpg'),
  require('./images/bw10.jpg'),
  require('./images/bw11.jpg'),
  require('./images/bw12.jpg'),
  require('./images/bw13.jpg'),
  require('./images/bw14.jpg'),
  require('./images/bw15.jpg'),
  require('./images/bw16.jpg'),
  require('./images/bw17.jpg'),
  require('./images/tree bw2.jpg'),
  require('./images/tree bw1.jpg'),
  require('./images/bw gate2.jpg'),
  require('./images/bw gate3.jpg'),
  require('./images/bw gate1.jpg'),
  require('./images/estate gate bw1.jpg'),
  require('./images/after rain bw1.jpg'),
  require('./images/nitelife5 bw.jpg'),
  require('./images/changing tire bw.jpg'),
  require('./images/bank bw1.jpg'),
  require('./images/school bw1.jpg'),
  require('./images/school bw2.jpg'),
  require('./images/school bw3.jpg'),
  require('./images/school bw4.jpg'),
  require('./images/HBG bw3.jpg'),
  require('./images/Mosque bw2.jpg'),
  require('./images/Islam worship bw1.jpg'),
  require('./images/open store front bw1.jpg'),
  require('./images/table tennis bw1.jpg'),
  require('./images/IMG-20220503-WA0000_2.jpg'),
  require('./images/IMG-20220503-WA0001_2.jpg'),
  require('./images/IMG-20220503-WA0002_2.jpg'),
  require('./images/IMG-20220503-WA0003_2.jpg'),
  require('./images/IMG-20220503-WA0004_2.jpg'),
  require('./images/IMG-20220503-WA0005_2.jpg'),
  require('./images/IMG-20220503-WA0011_3.jpg'),
  require('./images/IMG-20220503-WA0013_2.jpg'),
  require('./images/looking out bw1.jpg'),
  require('./images/looking out bw2.jpg'),
];

export default images;
